# Generated by Django 5.2.16 on 2026-09-19 20:20

import calendar_app.models
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_reminder_uid(apps, schema_editor):
    # Callable unique defaults evaluate once per AddField; give each row its own uid.
    Reminder = apps.get_model("calendar_app", "Reminder")
    for reminder in Reminder.objects.all():
        reminder.uid = uuid.uuid4().hex
        reminder.save(update_fields=["uid"])


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='uid',
            field=models.CharField(default=calendar_app.models._generate_reminder_uid, max_length=64),
        ),
        migrations.RunPython(backfill_reminder_uid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reminder',
            name='uid',
            field=models.CharField(default=calendar_app.models._generate_reminder_uid, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='CalendarKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
